apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-ebljqrda
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/jsmid/go-ebljqrda:azure-ab5f4437ccc7e57686cca8fd6a87fa4272bb5817
        name: container-image  
